name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Create Platform Files
        run: flutter create .

      - name: Fix Kotlin Version & Add Permissions
        run: |
          # تحديث إصدار Kotlin ليتوافق مع مكتبة الـ GPS
          sed -i "s/ext.kotlin_version = '[^']*'/ext.kotlin_version = '1.9.22'/g" android/build.gradle
          
          # إضافة صلاحيات الإنترنت والموقع
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>' android/app/src/main/AndroidManifest.xml
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>' android/app/src/main/AndroidManifest.xml

      - name: Generate Firebase Options
        run: |
          API_KEY=$(jq -r '.client[0].api_key[0].current_key' android/app/google-services.json)
          APP_ID=$(jq -r '.client[0].client_info.mobilesdk_app_id' android/app/google-services.json)
          PROJECT_ID=$(jq -r '.project_info.project_id' android/app/google-services.json)
          SENDER_ID=$(jq -r '.project_info.project_number' android/app/google-services.json)
          
          cat << DART_EOF > lib/firebase_options.dart
          import 'package:firebase_core/firebase_core.dart';
          const firebaseOptions = FirebaseOptions(
            apiKey: '${API_KEY}',
            appId: '${APP_ID}',
            messagingSenderId: '${SENDER_ID}',
            projectId: '${PROJECT_ID}',
          );
          DART_EOF

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: delivery-tracker-apk
          path: build/app/outputs/flutter-apk/app-release.apk
