name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Create Platform Files
        run: flutter create .

      - name: Inject Firebase Gradle Plugins (The Automation Hack)
        run: |
          # إدراج مكوّن فايربيز في ملف build.gradle الرئيسي
          sed -i '/plugins {/a \    id "com.google.gms.google-services" version "4.4.1" apply false' android/build.gradle
          # إدراج المكوّن في ملف build.gradle الخاص بالتطبيق
          sed -i '/plugins {/a \    id "com.google.gms.google-services"' android/app/build.gradle

          # إضافة صلاحية الإنترنت بشكل صريح للتطبيق في الـ Manifest
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: delivery-tracker-apk
          path: build/app/outputs/flutter-apk/app-release.apk
