name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Create Platform Files
        run: flutter create .

      - name: Hardcode Package Name and Inject Firebase
        run: |
          # 1. استبدال اسم الحزمة الافتراضي باسم الحزمة الخاص بك في كل ملفات الأندرويد
          find android/ -type f \( -name "*.gradle" -o -name "*.xml" -o -name "*.kt" -o -name "*.java" \) -exec sed -i 's/com.example.delivery_tracker/com.delivery.mr3bdo/g' {} +
          find android/ -type f \( -name "*.gradle" -o -name "*.xml" -o -name "*.kt" -o -name "*.java" \) -exec sed -i 's/com.example.delivery/com.delivery.mr3bdo/g' {} +

          # 2. إضافة إصدار الفايربيز في ملف settings.gradle
          sed -i '/plugins {/a \    id "com.google.gms.google-services" version "4.4.1" apply false' android/settings.gradle
          
          # 3. إضافة تعريف الفايربيز لملف التطبيق build.gradle
          sed -i '/plugins {/a \    id "com.google.gms.google-services"' android/app/build.gradle
          
          # 4. إضافة صلاحية الإنترنت بشكل صريح في الـ Manifest
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET"/>' android/app/src/main/AndroidManifest.xml

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: delivery-tracker-apk
          path: build/app/outputs/flutter-apk/app-release.apk
